/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cz' at '15-12-24 下午10:12' with Gradle 2.10
 *
 * @author cz, @date 15-12-24 下午10:12
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
